In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Đường dẫn đến file CSV
file_path = '/home/ducanhhh/Dynamic_Feature-main/ERC-20 Log/Dataset/exp_erc20_trans.csv'

# Đọc dữ liệu
df = pd.read_csv(file_path)
print(f"Dữ liệu có {df.shape[0]:,} dòng và {df.shape[1]} cột.")
df.head()

Dữ liệu có 6,347,943 dòng và 15 cột.

,0xe0a3613bc5ec9e5ebe4bbb2bf739dbb16819a3f0006df68a228900d739e1e83d,51370,0x0854f5f57dd738fc4bd119daa5c8e8f605bf741784874a6ff6889d92e72dfe25,3919820,48,0x7fe2b88f2e4858de375832fbf54ac7cf1a78ca51,0xa74476443119a942de498590fe1f2454d7d4ac0d,0,300000,50000000000,0xa9059cbb000000000000000000000000fd691c23a3f5cc7d8ed8626a5caf67fd8dce3af6000000000000000000000000000000000000000000000002c72551731fb37400,1498253896,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,0xa214a3ff0c5fd452cd45d8ca7fa070f983d685fddff5...,51323,0x0843e7258801b2bb6d58332fed2008d78d72966e4cc0...,3919706,39,0x7fe2b88f2e4858de375832fbf54ac7cf1a78ca51,0xa74476443119a942de498590fe1f2454d7d4ac0d,0,300000,50000000000,0xa9059cbb000000000000000000000000d8b632ef3cfa...,1498251906,NaN,NaN,NaN
1,0x40545521021a0e2cb874e511e9cd7026d1b7943ecc58...,2204,0x773635c4ec93e56acf9eb9cd87930c5361e98f9c7391...,3920072,32,0xb1a1fda9d99ae21dc0d17c86460286c651def45d,0xa54ddc7b3cce7fc8b1e3fa0256d0db80d2c10970,0,77221,4000000000,0xa9059cbb00000000000000000000000053b1b429a4ce...,1498258030,NaN,NaN,NaN
2,0x1e76bc5ca8991be95637b2f99b026af29c3e8458a5bb...,372733,0xec54746ecfd682184a82da877f73df87580bd8870357...,3920320,0,0xfbb1b73c4f0bda4f67dca266ce6ef42f520fbb98,0x960b236a07cf122663c4303350609a66a7b288c0,0,256386,75000000000,0xa9059cbb00000000000000000000000060adcbe1cd91...,1498262650,NaN,NaN,NaN
3,0xd0edca03b99462ae306b50853c748e839c849446f1a8...,372739,0xa4b11a5ae390b989c94df2b8b81589dbdc3dca215ea0...,3920323,0,0xfbb1b73c4f0bda4f67dca266ce6ef42f520fbb98,0x667088b212ce3d06a1b553a7221e1fd19000d9af,0,187234,75000000000,0xa9059cbb00000000000000000000000060adcbe1cd91...,1498262670,NaN,NaN,NaN
4,0x2b1dc14a4ecb446021b6d9b025e90db27e9e5b444ff1...,372741,0x8f5e8eade734b629575a40ed854a83d9e6589ea4f25d...,3920327,0,0xfbb1b73c4f0bda4f67dca266ce6ef42f520fbb98,0xfa05a73ffe78ef8f1a739473e462c54bae6567d9,0,202551,75000000000,0xa9059cbb00000000000000000000000060adcbe1cd91...,1498262737,NaN,NaN,NaN

In [3]:
# Thông tin tổng quan
df.info()

# Kiểm tra giá trị thiếu
print("\nSố lượng giá trị thiếu:")
print(df.isnull().sum())

# Mô tả thống kê
df.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6347943 entries, 0 to 6347942
Data columns (total 15 columns):
 #   Column                                                                                                                                      Dtype
---  ------                                                                                                                                      -----
 0   0xe0a3613bc5ec9e5ebe4bbb2bf739dbb16819a3f0006df68a228900d739e1e83d                                                                          object
 1   51370                                                                                                                                       int64
 2   0x0854f5f57dd738fc4bd119daa5c8e8f605bf741784874a6ff6889d92e72dfe25                                                                          object
 3   3919820                                                                                                                                     int64
 4   48                                                                                                                                          int64
 5   0x7fe2b88f2e4858de375832fbf54ac7cf1a78ca51                                                                                                  object
 6   0xa74476443119a942de498590fe1f2454d7d4ac0d                                                                                                  object
 7   0                                                                                                                                           object
 8   300000                                                                                                                                      int64
 9   50000000000                                                                                                                                 int64
 10  0xa9059cbb000000000000000000000000fd691c23a3f5cc7d8ed8626a5caf67fd8dce3af6000000000000000000000000000000000000000000000002c72551731fb37400  object
 11  1498253896                                                                                                                                  int64
 12  Unnamed: 12                                                                                                                                 float64
 13  Unnamed: 13                                                                                                                                 float64
 14  Unnamed: 14                                                                                                                                 float64
dtypes: float64(3), int64(6), object(6)
memory usage: 726.5+ MB

Số lượng giá trị thiếu:
0xe0a3613bc5ec9e5ebe4bbb2bf739dbb16819a3f0006df68a228900d739e1e83d                                                                                  0
51370                                                                                                                                               0
0x0854f5f57dd738fc4bd119daa5c8e8f605bf741784874a6ff6889d92e72dfe25                                                                                  0
3919820                                                                                                                                             0
48                                                                                                                                                  0
0x7fe2b88f2e4858de375832fbf54ac7cf1a78ca51                                                                                                          0
0xa74476443119a942de498590fe1f2454d7d4ac0d                                                                                                       1260
0                                                                                                                                                   0
300000                                                                                                                                              0
50000000000                                                                                                                                         0
0xa9059cbb000000000000000000000000fd691c23a3f5cc7d8ed8626a5caf67fd8dce3af6000000000000000000000000000000000000000000000002c72551731fb37400          0
1498253896                                                                                                                                          0
Unnamed: 12                                                                                                                                   5960923
Unnamed: 13                                                                                                                                   5960923
Unnamed: 14                                                                                                                                   5960544
dtype: int64

,0xe0a3613bc5ec9e5ebe4bbb2bf739dbb16819a3f0006df68a228900d739e1e83d,51370,0x0854f5f57dd738fc4bd119daa5c8e8f605bf741784874a6ff6889d92e72dfe25,3919820,48,0x7fe2b88f2e4858de375832fbf54ac7cf1a78ca51,0xa74476443119a942de498590fe1f2454d7d4ac0d,0,300000,50000000000,0xa9059cbb000000000000000000000000fd691c23a3f5cc7d8ed8626a5caf67fd8dce3af6000000000000000000000000000000000000000000000002c72551731fb37400,1498253896,Unnamed: 12,Unnamed: 13,Unnamed: 14
count,6347943,6.347943e+06,6347943,6.347943e+06,6.347943e+06,6347943,6346683,6347943,6.347943e+06,6.347943e+06,6347943,6.347943e+06,3.870200e+05,3.870200e+05,387399.000000
unique,6347943,NaN,4109685,NaN,NaN,1037948,51099,121261,NaN,NaN,5179890,NaN,NaN,NaN,NaN
top,0x10ee0a3ab678f2d20a6b441e5df118215774e70cf21e...,NaN,0x78882b79bfa67249ea376a231c2003ed77330a61464a...,NaN,NaN,0x2ad7cb7ce3b5cbaa02481e416d85f5954748d292,0xdac17f958d2ee523a2206206994597c13d831ec7,0,NaN,NaN,0x,NaN,NaN,NaN,NaN
freq,1,NaN,365,NaN,NaN,62284,1284727,5969385,NaN,NaN,102142,NaN,NaN,NaN,NaN
mean,NaN,1.501565e+05,NaN,9.603175e+06,9.249219e+01,NaN,NaN,NaN,3.762469e+05,5.533793e+10,NaN,1.582298e+09,1.573600e+11,1.050521e+10,1.999022
std,NaN,6.558576e+05,NaN,2.742472e+06,7.168541e+01,NaN,NaN,NaN,1.026422e+06,3.362613e+11,NaN,3.799785e+07,1.598169e+11,3.717774e+10,0.031263
min,NaN,0.000000e+00,NaN,3.919706e+06,0.000000e+00,NaN,NaN,NaN,2.472800e+04,0.000000e+00,NaN,1.498252e+09,1.600000e+10,0.000000e+00,1.000000
25%,NaN,1.200000e+01,NaN,7.514430e+06,3.700000e+01,NaN,NaN,NaN,6.001000e+04,9.000000e+09,NaN,1.554552e+09,8.132472e+10,1.500000e+09,2.000000
50%,NaN,2.520000e+02,NaN,9.922406e+06,7.900000e+01,NaN,NaN,NaN,1.000000e+05,3.000000e+10,NaN,1.587561e+09,1.203062e+11,1.825346e+09,2.000000
75%,NaN,7.081000e+03,NaN,1.184565e+07,1.320000e+02,NaN,NaN,NaN,2.071280e+05,7.645950e+10,NaN,1.613183e+09,1.761876e+11,2.000000e+09,2.000000
max,NaN,1.090574e+07,NaN,1.429775e+07,1.360000e+03,NaN,NaN,NaN,2.957358e+07,5.798460e+14,NaN,1.646093e+09,9.871728e+12,6.006000e+12,2.000000

In [4]:
# Giả sử cột nhãn là 'label' hoặc 'isp' hoặc 'is_phishing'
if 'label' in df.columns:
    label_col = 'label'
elif 'isp' in df.columns:
    label_col = 'isp'
elif 'is_phishing' in df.columns:
    label_col = 'is_phishing'
else:
    label_col = None

if label_col:
    print(df[label_col].value_counts())
    sns.countplot(data=df, x=label_col)
    plt.title("Phân bố lớp (Label distribution)")
    plt.show()
else:
    print("Không tìm thấy cột nhãn để phân tích phân phối.")

Không tìm thấy cột nhãn để phân tích phân phối.